# Generated by Django 3.2.7 on 2021-09-15 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examining', '0001_initial'),
        ('palographic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palographic',
            name='test',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='palographic',
            name='examining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palographic_examining', to='examining.examining'),
        ),
        migrations.AlterField(
            model_name='palographic',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palographic_psychologist', to=settings.AUTH_USER_MODEL),
        ),
    ]
