# Generated by Django 3.2.7 on 2021-09-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palographic', '0002_auto_20210915_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palographic',
            name='schooling',
            field=models.CharField(max_length=30),
        ),
    ]
