CREATE TABLE tb_ceps (pk_id_cep integer NOT NULL, cep integer, endereco_completo character varying(999), cidade character varying(999), estado character varying(999));
ALTER TABLE tb_ceps ALTER COLUMN pk_id_cep ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME tb_ceps_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE MAXVALUE 999999 CACHE 1);
INSERT INTO tb_ceps (cep, endereco_completo, cidade, estado) VALUES ('77021642', '404 Sul Avenida LO 9', 'palmas', 'tocantins');
INSERT INTO tb_ceps (cep, endereco_completo, cidade, estado) VALUES ('08240001', 'Rua 23 de Novembro', 'Sao Paulo', 'Sao Paulo');
INSERT INTO tb_ceps (cep, endereco_completo, cidade, estado) VALUES ('23555240', 'Rua 1, Est do Zepelin', 'Rio de Janeiro', 'Rio de Janeiro');
SELECT pg_catalog.setval('tb_ceps_id_seq', 1, true);
ALTER TABLE ONLY tb_ceps ADD CONSTRAINT tb_ceps_pkey PRIMARY KEY (pk_id_cep);