# Generated by Django 3.2.7 on 2021-09-16 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palographic', '0002_auto_20210915_1745'),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='distance_between_palos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='income',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='nor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='palographic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_palographic', to='palographic.palographic'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='palos_size',
            field=models.FloatField(),
        ),
    ]
