# Generated by Django 3.2.7 on 2021-09-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20210916_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='income',
            field=models.CharField(max_length=40),
        ),
    ]
