# Generated by Django 3.2.7 on 2021-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('gender', models.IntegerField()),
                ('schooling', models.IntegerField()),
            ],
            options={
                'verbose_name': 'examining',
            },
        ),
    ]
