# Generated by Django 3.2.7 on 2021-09-15 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('palographic', '0002_auto_20210915_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productivity', models.IntegerField()),
                ('nor', models.DecimalField(decimal_places=8, max_digits=11)),
                ('income', models.CharField(max_length=40)),
                ('distance_between_palos', models.DecimalField(decimal_places=8, max_digits=11)),
                ('palos_size', models.DecimalField(decimal_places=8, max_digits=11)),
                ('impulsiveness', models.IntegerField()),
                ('difference_sum', models.IntegerField()),
                ('palographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palographic_examining', to='palographic.palographic')),
            ],
            options={
                'verbose_name': 'analysis',
            },
        ),
    ]
