# Generated by Django 3.2.7 on 2021-09-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examining',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='examining',
            name='schooling',
            field=models.IntegerField(max_length=30),
        ),
    ]
