# Generated by Django 3.2.7 on 2021-09-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examining', '0002_auto_20210921_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examining',
            name='schooling',
            field=models.CharField(max_length=30),
        ),
    ]
